@baseUrl = http://localhost:3000
@baseId = {{create_user.response.body.user.user_id}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "user_cpf": "04157548121",
  "user_name": "Juvenal",
  "user_email": "Jav3541a1lgarci1a@gmail.com",
  "user_phone": "+5513914271364",
  "user_company_name": "Supermercado",
  "user_company_cnpj": "514131442/0000"
}

###

# @name add_credits
PUT {{baseUrl}}/clients/add_credits
Content-Type: application/json

{
  "user_uuid": "362b1e55-ea8b-4c66-9f17-f240545264ef",
  "credits":3
}

###

# @name get_client
GET {{baseUrl}}/clients/362b1e55-ea8b-4c66-9f17-f240545264ef
Content-Type: application/json

###

# @name change_plan
PUT {{baseUrl}}/clients/plan
Content-Type: application/json

{
  "user_uuid": "362b1e55-ea8b-4c66-9f17-f240545264ef",
  "plan_type":"pre-pago"
}

###

# @name change_limit
PUT {{baseUrl}}/clients/limit
Content-Type: application/json

{
  "user_uuid": "362b1e55-ea8b-4c66-9f17-f240545264ef",
  "limit":3
}

###

# @name change_limit
POST {{baseUrl}}/platforms
Content-Type: application/json

{
  "platform_name":"Messenger",
  "platform_cost":1
}

###

# @name change_limit
POST {{baseUrl}}/messages/send
Content-Type: application/json

{
  "message_text":"WhatsApp",
  "message_to":"40028922",
  "user_uuid": "362b1e55-ea8b-4c66-9f17-f240545264ef",
  "platform_id": 1
}

