@baseUrl = http://localhost:3000
@baseId = {{create_user.response.body.user.user_id}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "cpf": "04157338221",
  "name": "Juvenal",
  "email": "Jav31algarci1a@gmail.com",
  "phone": "+5513936271364",
  "company_name": "Supermercado",
  "company_cnpj": "513131442/0000"
}

###

# @name send_message
POST {{baseUrl}}/message/send
Content-Type: application/json

{
    "user_id":2,
    "text":"Compre meu curso",
    "is_whatsapp":true,
    "phone":"14996278264"
}

###

# @name add_credits
PUT {{baseUrl}}/clients/add_credits
Content-Type: application/json

{
  "user_id":2,
  "credits":0.5
}

###

# @name get_client
GET {{baseUrl}}/clients/2
Content-Type: application/json

###

# @name change_plan
PUT {{baseUrl}}/clients/plan
Content-Type: application/json

{
  "user_id":2,
  "plan_type":"pos-pago"
}

###

# @name change_limit
PUT {{baseUrl}}/clients/limit
Content-Type: application/json

{
  "user_id":2,
  "limit":3
}

