version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: prismadb
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prisma -d prismadb -P prismapassword']
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://prisma:prismapassword@postgres:5432/prismadb
    ports:
      - '3000:3000'
    depends_on:
      - postgres
