version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://prisma:prismapassword@postgres:5432/prismadb
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: prismadb
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
